### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'find_all'

### ISSUE THREAD

**Issue by ihabpalamino** [MatthewWolff/TwitterScraper#11]
[from  twitterscraper import  query_tweets
import datetime as dt
import pandas as pd
begin_date=dt.date(2023,4,2)
begin_fin=dt.date(2023,5,2)
limits=1000
lang='english'
# user='elonmusk'
tweets=query_tweets("elonmusk",begindate=begin_date,enddate=begin_fin,limit=limits,lang=lang)

after executing this code i get this error
Traceback (most recent call last):
  File "C:\Users\HP Probook\PycharmProjects\firstproject\TweetsSraper.py", line 23, in <module>
    from  twitterscraper import  query_tweets
  File "C:\Users\HP Probook\PycharmProjects\firstproject\venv\lib\site-packages\twitterscraper\__init__.py", line 13, in <module>
    from twitterscraper.query import query_tweets
  File "C:\Users\HP Probook\PycharmProjects\firstproject\venv\lib\site-packages\twitterscraper\query.py", line 76, in <module>
    proxies = get_proxies()
  File "C:\Users\HP Probook\PycharmProjects\firstproject\venv\lib\site-packages\twitterscraper\query.py", line 49, in get_proxies
    list_tr = table.find_all('tr')
AttributeError: 'NoneType' object has no attribute 'find_all'](url)

**Comment by MatthewWolff** [comment]
This isn't the right repo for whatever issue you're having, I don't have any code that looks like that. There is no query_tweets method in my codebase

**Comment by ihabpalamino** [comment]
okey so would you help me to know how to scrape informations tweets from a tweeter username for example i want captions of tweets tweeted by elonmusk with number of likes and comments and id...is that possible and how?
